export interface StatusInterface {
  code: number;
  title: string;
  description: string;
}

export const codes: StatusInterface[] = [
  { code: 100, title: "Continue", description: "Сервер получил начальную часть запроса, и клиент может продолжить отправку данных." },
  { code: 101, title: "Switching Protocols", description: "Клиент запросил изменение протокола, и сервер согласился на это." },
  { code: 102, title: "Processing", description: "Сервер обрабатывает запрос, но ответа пока нет." },
  { code: 200, title: "OK", description: "Запрос успешно выполнен." },
  { code: 201, title: "Created", description: "Запрос выполнен, и ресурс был создан." },
  { code: 202, title: "Accepted", description: "Запрос принят, но обработка еще не завершена." },
  { code: 203, title: "Non-Authoritative Information", description: "Ответ содержит информацию, которая отличается от оригинального ресурса." },
  { code: 204, title: "No Content", description: "Сервер успешно обработал запрос, но не возвращает данных." },
  { code: 205, title: "Reset Content", description: "Сервер обработал запрос и требует сбросить представление документа." },
  { code: 206, title: "Partial Content", description: "Сервер возвращает только часть данных, запрошенных клиентом." },
  { code: 207, title: "Multi-Status", description: "Ответ содержит несколько статус-кодов для разных частей запроса." },
  { code: 208, title: "Already Reported", description: "Элементы уже были перечислены в предыдущем ответе." },
  { code: 226, title: "IM Used", description: "Ответ является результатом манипуляций над текущим экземпляром ресурса." },
  { code: 300, title: "Multiple Choices", description: "Запрос может иметь несколько возможных ответов." },
  { code: 301, title: "Moved Permanently", description: "Ресурс был перемещён на постоянный новый адрес." },
  { code: 302, title: "Found", description: "Ресурс временно доступен по другому адресу." },
  { code: 303, title: "See Other", description: "Ресурс можно найти по другому URI, используя GET-запрос." },
  { code: 304, title: "Not Modified", description: "Ресурс не изменялся с момента последнего запроса." },
  { code: 305, title: "Use Proxy", description: "Доступ к ресурсу возможен только через указанный прокси." },
  { code: 307, title: "Temporary Redirect", description: "Ресурс временно доступен по другому адресу, но метод запроса сохраняется." },
  { code: 308, title: "Permanent Redirect", description: "Ресурс перемещён на новый адрес навсегда, с сохранением метода запроса." },
  { code: 400, title: "Bad Request", description: "Сервер не может обработать запрос из-за ошибки в синтаксисе." },
  { code: 401, title: "Unauthorized", description: "Для доступа к ресурсу требуется аутентификация." },
  { code: 402, title: "Payment Required", description: "Предназначен для использования в будущем." },
  { code: 403, title: "Forbidden", description: "У клиента нет прав на доступ к ресурсу." },
  { code: 404, title: "Not Found", description: "Запрошенный ресурс не найден." },
  { code: 405, title: "Method Not Allowed", description: "Запрошенный метод не поддерживается для данного ресурса." },
  { code: 406, title: "Not Acceptable", description: "Сервер не может отправить данные в запрошенном формате." },
  { code: 407, title: "Proxy Authentication Required", description: "Для доступа к ресурсу через прокси требуется аутентификация." },
  { code: 408, title: "Request Timeout", description: "Сервер ожидает запрос слишком долго." },
  { code: 409, title: "Conflict", description: "Запрос конфликтует с текущим состоянием ресурса." },
  { code: 410, title: "Gone", description: "Ресурс был удалён и больше недоступен." },
  { code: 411, title: "Length Required", description: "Необходимо указать длину содержимого запроса." },
  { code: 412, title: "Precondition Failed", description: "Предусловия запроса не выполнены." },
  { code: 413, title: "Payload Too Large", description: "Размер запроса превышает допустимые пределы сервера." },
  { code: 414, title: "URI Too Long", description: "URI запроса слишком длинный для обработки сервером." },
  { code: 415, title: "Unsupported Media Type", description: "Формат данных в запросе не поддерживается сервером." },
  { code: 416, title: "Range Not Satisfiable", description: "Указанный диапазон не может быть выполнен для ресурса." },
  { code: 417, title: "Expectation Failed", description: "Ожидания клиента, указанные в заголовке, не могут быть выполнены." },
  { code: 418, title: "I'm a teapot", description: "Код ошибки из шутливой спецификации HTCPCP." },
  { code: 421, title: "Misdirected Request", description: "Сервер не может обработать запрос, так как он адресован другому серверу." },
  { code: 422, title: "Unprocessable Entity", description: "Сервер не может обработать запрос из-за ошибок в его содержимом." },
  { code: 423, title: "Locked", description: "Ресурс заблокирован." },
  { code: 424, title: "Failed Dependency", description: "Запрос не выполнен из-за ошибки в предыдущем запросе." },
  { code: 425, title: "Too Early", description: "Сервер не хочет рисковать обработкой запроса, который может быть воспроизведён." },
  { code: 426, title: "Upgrade Required", description: "Для выполнения запроса клиенту необходимо обновить протокол." },
  { code: 428, title: "Precondition Required", description: "Сервер требует выполнения условий в запросе." },
  { code: 429, title: "Too Many Requests", description: "Клиент отправил слишком много запросов за короткий период времени." },
  { code: 431, title: "Request Header Fields Too Large", description: "Заголовки запроса слишком большие для обработки сервером." },
  { code: 451, title: "Unavailable For Legal Reasons", description: "Доступ к ресурсу ограничен по юридическим причинам." },
  { code: 500, title: "Internal Server Error", description: "Сервер столкнулся с внутренней ошибкой и не может обработать запрос." },
  { code: 501, title: "Not Implemented", description: "Сервер не поддерживает запрошенный метод." },
  { code: 502, title: "Bad Gateway", description: "Сервер получил недействительный ответ от вышестоящего сервера." },
  { code: 503, title: "Service Unavailable", description: "Сервер временно недоступен для обработки запросов." },
  { code: 504, title: "Gateway Timeout", description: "Сервер не получил ответ от вышестоящего сервера вовремя." },
  { code: 505, title: "HTTP Version Not Supported", description: "Версия HTTP-протокола в запросе не поддерживается сервером." },
  { code: 506, title: "Variant Also Negotiates", description: "Ошибка конфигурации сервера." },
  { code: 507, title: "Insufficient Storage", description: "Сервер не может сохранить данные для выполнения запроса." },
  { code: 508, title: "Loop Detected", description: "Сервер обнаружил бесконечный цикл при обработке запроса." },
  { code: 510, title: "Not Extended", description: "Для выполнения запроса требуется дополнительное расширение." },
  { code: 511, title: "Network Authentication Required", description: "Клиент должен пройти аутентификацию для получения доступа к сети." },
];

